language: node_js
script:
  - npm run build:dist
node_js:
  - "iojs"
  - "7"
after_script:
  NODE_ENV=test nyc mocha --compilers ts:ts-node/register tests/**/**/**/*.spec.ts && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

